from math import sqrt

x = None
match x:
    case 0:
        ...
    case "Hello, Pycon":
        ...
    case 1 | 2:
        ...
    case str():
        ...
    case int(1):
        ...
    case float(1):
        ...
    case tuple((1, 2, 3, 4)):
        ...
    case ["move", direction]:
        ...
    case ["python", "is", *adjectives]:
        ...
    case ["twenty", ("five" | "twentyfive") as second_half]:
        ...
    case {"name": name, "greeting": greeting, **rest}:
        ...
    case {"list": ["first item", *rest] as my_list, **kwargs}:
        ...
    case int(x) if sqrt(x) % 2 == 0:
        ...
    case _:
        ...
